#ifndef MAIN_DIALOG_DEF_H
#define MAIN_DIALOG_DEF_H
enum MainDialogType_e
{
    MAIN_DIALOG_TYPE_UNKNOW,
    MAIN_DIALOG_TYPE_SAMPLE,
    MAIN_DIALOG_TYPE_PREVIEW,
    MAIN_DIALOG_TYPE_FILE_MANAGER,
    MAIN_DIALOG_TYPE_SETTING,
};
#endif // MAIN_DIALOG_DEF_H
