#ifndef MAIN_WIDGET_DEF_H
#define MAIN_WIDGET_DEF_H
enum MainWidgetType_e
{
    MAIN_WIDGET_TYPE_UNKNOW,
    MAIN_WIDGET_TYPE_SAMPLE,
    MAIN_WIDGET_TYPE_PREVIEW,
    MAIN_WIDGET_TYPE_FILE_MANAGER,
    MAIN_WIDGET_TYPE_SETTING,
};
#endif // MAIN_WIDGET_DEF_H
